export { createMockClient } from "./client.js"
export type { MockClient, MockClientOptions } from "./client.js"
export { createMockHost, defaultMockHostState, mockTip, mockAccountState } from "./host.js"
export type { MockHost, MockHostOptions, MockHostState } from "./host.js"
export { dispatchMessageEvent } from "./client.js"
export { setHostWindow } from "../client.js"
